### ISSUE TITLE
Server quits after latest dedicated server update

### ISSUE THREAD

**Issue by hrdejong** [assetto-corsa-web/accweb#132]
After updating the executable to all servers they quit after a while. Also updated to latest version of accweb but problem still exists.

Last lines in accweb log:
==ERR: This server is only supported on Windows operating systems. Running WINE may work dependent on your settings, but there are differences that affect the user's experience negatively.
Sent lobby registration request for misano_2020

Last lines in logfile on commandline:
131765: ==ERR: This server isn't running on a supported platform AND is configured in a way that causes problems for other users.
131765: ==ERR: You can try to set ignorePrematureDisconnects to 0, but better run the server on supported operating systems.

**Comment by Kugelschieber** [comment]
ignorePrematureDisconnects needs to be added.

**Comment by hrdejong** [comment]
Where do you add this?

**Comment by Kugelschieber** [comment]
I mean to accweb, not by you right now.

**Comment by hrdejong** [comment]
Ah, okay ;-)

**Comment by dinuxlt** [comment]
I think related post from ACC developers: https://www.assettocorsa.net/forum/index.php?threads/since-1-7-dedicated-servers-running-on-linux-do-not-timeout-disconnected-users.68366/page-3#post-1187008

**Comment by 33Fraise33** [comment]
I tried adding `ignorePrematureDisconnects` to the settings.json file and importing it but it seems the setting is being removed. 

Please add this feature, info on the setting:

```
Removes a (very good) fix where users can randomly lose the
connection. There is no sane reason to turn this off.
1 – default: less arbitrary connections lost
0 – more timeouts, but strict disconnection of anyone who
appears inactive for 5 seconds. Can be useful on unsupported
platforms where TCP sockets act differently
```
0 will be needed for the docker container or wine. 

It's a shame that there is no real linux support but I understand it's a resource constraint

**Comment by Kugelschieber** [comment]
Fixed: https://github.com/assetto-corsa-web/accweb/releases/tag/v1.13.2

**Comment by hrdejong** [comment]
Nice! Thanks for the work, will update right now :-).

**Comment by hrdejong** [comment]
Tried twice but no go, still quits on me and get the same error :(. I would assume that recreation of the server configs is not needed?

**Comment by Kugelschieber** [comment]
Shouldn't be. What's the error message?

**Comment by hrdejong** [comment]
still get the same error, completely renamed the old server folder en copied the new one. After that I relaced the config folder and the config.yml with my old ones (don't see anything different in the config.yml.

131309: ==ERR: This server isn't running on a supported platform AND is configured in a way that causes problems for other users.
131309: ==ERR: You can try to set ignorePrematureDisconnects to 0, but better run the server on supported operating systems.

**Comment by hrdejong** [comment]
Maybe I'm not doing the right thing... you still need to change the option to 0 in a file?

**Comment by Kugelschieber** [comment]
Yes, but you can now do that on the web interface.

**Comment by hrdejong** [comment]
It's already set when I click edit but saved it anyway. First server still running, will wait for a while if they keep running.

**Comment by Kugelschieber** [comment]
Probably, the config needs to be updated with the new field. I close this for now.

**Comment by hrdejong** [comment]
Still running so seems okay now. Thanks!
